#ifndef AUTOCROSS_DEFAULTS_H
#define AUTOCROSS_DEFAULTS_H

#define DEF_RAMP_START_AUTOCROSS 70
#define DEF_RAMP_END_AUTOCROSS   0
#define DEF_RAMP_TIME_AUTOCROSS  250

#define DEF_RPM_LIMIT_1_2_AUTOCROSS       11300
#define DEF_RPM_LIMIT_2_3_AUTOCROSS       11300
#define DEF_RPM_LIMIT_3_4_AUTOCROSS       11300

#define DEF_SPEED_LIMIT_1_2_AUTOCROSS     47
#define DEF_SPEED_LIMIT_2_3_AUTOCROSS     65
#define DEF_SPEED_LIMIT_3_4_AUTOCROSS     80

#endif